In [1]:
import os
import numpy as np
import pandas as pd


In [2]:
os.listdir()

['.ipynb_checkpoints',
 'adult.data.csv',
 'adult.data.prepared.csv',
 'adult.data.txt',
 'adult.test.prepared.csv',
 'adult.test.txt',
 'Colnames.txt',
 'DataCleaning.ipynb',
 'ex01_group38_scheu_R.ipynb',
 'ex2_marc.ipynb',
 'ex3.R',
 'ex3_logit.ipynb',
 'MachLearnExercise01.ipynb',
 'MachLearnExercise02.ipynb',
 'MachLearnExercises03.ipynb']

In [3]:
train = pd.read_csv('adult.data.prepared.csv', header = None)
train.head(10)

0       1              2             3             4               5   \
0  age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week   
1   39   77516             13          2174             0              40   
2   50   83311             13             0             0              13   
3   38  215646              9             0             0              40   
4   53  234721              7             0             0              40   
5   28  338409             13             0             0              40   
6   37  284582             14             0             0              40   
7   49  160187              5             0             0              16   
8   52  209642              9             0             0              45   
9   31   45781             14         14084             0              50   

            6           7        8        9        10        11           12  
0  higher_educ  lower_educ  is_male  gov_emp  private  self_emp  high_income  
1            1           0        1        1        0         0            0  
2            1           0        1        0        0         1            0  
3            0           0        1        0        1         0            0  
4            0           1        1        0        1         0            0  
5            1           0        0        0        1         0            0  
6            1           0        0        0        1         0            0  
7            0           1        0        0        1         0            0  
8            0           0        1        0        0         1            1  
9            1           0        0        0        1         0            1

In [5]:
X_train = np.array(train[1:,0:12], dtype = 'float64')
X_train = np.pad(X_train,1,'constant',constant_values=(1))[1:X_train.shape[0]+1,0:X_train.shape[1]+1]
Y_train = np.array(train[1:,12:], dtype = 'int')
Y_train

array([[0],
       [0],
       [0],
       ..., 
       [0],
       [0],
       [1]])

For the start of the algorithm set abitrarily all tetas to 1

In [14]:
teta = np.ones([1,X_train.shape[1]], dtype = 'float64')
xi = X_train[0,:]
xi = X_train[0:2,:]

The formular for <b>h_teta(x) = exp(transpose(teta).dot(X))/ 1 - exp(transpose(teta).dot(X))</b><br>
This produces overflow for high transpose(teta).dot(X) therefore we transform the formular to <br>
<b>h_teta = 0.2 + 0.5 * tanh(transpose(teta).dot(X) / 2)</b><br>
https://en.wikipedia.org/wiki/Logistic_function
<br> <b>to do</b> dimensions of teta are wrongly defined

In [34]:
def get_h_teta(teta, xi ):
    h_teta = np.transpose(0.5 + 0.5 * np.tanh((teta.dot(np.transpose(xi)) / 2)))
    return(h_teta)

In [43]:
h_teta = get_h_teta(teta, X_train)
h_teta.shape
#Y_train.shape

(30725, 1)

In [44]:
deriva = np.transpose(X_train).dot(Y_train - h_teta)
print(deriva)
deriva.shape

[[ -2.30750000e+04]
 [ -8.44714000e+05]
 [ -4.39417150e+09]
 [ -2.22347000e+05]
 [ -3.41534700e+06]
 [ -1.23479600e+06]
 [ -9.08430000e+05]
 [ -3.84300000e+03]
 [ -3.59000000e+03]
 [ -1.42700000e+04]
 [ -3.01000000e+03]
 [ -1.77330000e+04]
 [ -2.31100000e+03]]


(13, 1)

In [52]:
const = 0.01
teta_neu = teta + const * np.transpose(deriva)
print(teta.shape)
print(teta_neu.shape)
teta_neu


(1, 13)
(1, 13)


array([[ -2.29750000e+02,  -8.44614000e+03,  -4.39417140e+07,
         -2.22247000e+03,  -3.41524700e+04,  -1.23469600e+04,
         -9.08330000e+03,  -3.74300000e+01,  -3.49000000e+01,
         -1.41700000e+02,  -2.91000000e+01,  -1.76330000e+02,
         -2.21100000e+01]])