<h3>Exercise</h3>

In [1]:
import os
import pandas
import numpy as np
import scipy.stats

os.listdir()


['.ipynb_checkpoints',
 'ex01_group38_scheu_R.ipynb',
 'ex2_marc.ipynb',
 'MachLearnExercise01.ipynb',
 'MachLearnExercise02.ipynb']

In [2]:
with open('boston.csv', 'r') as f:
    content = f.readlines()
content = [x.strip() for x in content] 

#(content[0] + content[1]).split()

FileNotFoundError: [Errno 2] No such file or directory: 'boston.csv'

In [3]:
a = range(0,len(content),2)
b = range(1,len(content)+1,2)
content = [content[i] + ' ' + content[j] for i,j in zip(a,b)]
content[0]

In [4]:
d = np.array([line.split() for line in content],dtype = "float")
np.set_printoptions(precision=4)

In [5]:
print([format(value, '.8f') for value in d.mean(axis = 0)])
print([format(value, '.8f') for value in d.std(axis = 0)])
print([format(value, '.8f') for value in d.var(axis = 0)])

['3.61352356', '11.36363636', '11.13677866', '0.06916996', '0.55469506', '6.28463439', '68.57490119', '3.79504269', '9.54940711', '408.23715415', '18.45553360', '356.67403162', '12.65306324', '22.53280632']
['8.59304135', '23.29939569', '6.85357058', '0.25374293', '0.11576312', '0.70192251', '28.12103257', '2.10362836', '8.69865112', '168.37049504', '2.16280519', '91.20460745', '7.13400164', '9.18801155']
['73.84035967', '542.86183974', '46.97142974', '0.06438548', '0.01340110', '0.49269522', '790.79247282', '4.42525226', '75.66653127', '28348.62359981', '4.67772630', '8318.28042050', '50.89397935', '84.41955616']


In [8]:
with open('boston_header.csv', 'r') as f:
    header = f.readlines()
header = [x.strip() for x in content] 

2 Simple regression

In [55]:
def lm_simple(x,y):
    b1 = (x-x.mean()).dot((Y - Y.mean())) / (x-x.mean()).dot((x - x.mean()))
    b0 = Y.mean() - b1 * x.mean()

    y_hat = b0 + b1 * x
    RSS = (y-y_hat).dot(y-y_hat)
    SE = RSS / (y_hat-y_hat.mean()).dot(y_hat-y_hat.mean()) * 1/(len(x)-2)
    t_value = b1 / SE
    p_value = scipy.stats.norm.pdf(t_value, loc=0, scale=1) 
    return (b1, p_value)

In [45]:
Y = d[:,d.shape[1]-1:]
X = d[:,0:d.shape[1]-1]
y = np.reshape(Y,[506,])
x =  X[:,3]

In [56]:
lm_simple(x=x,y=y)

(array([ 6.3462]), array([  1.9395e-138]))

In [80]:
coef_p = [lm_simple(X[:,i],y) for i in range(0,d.shape[1]-1)]
#coef_p.reshape([13,2])
coef_p

[(array([-0.4152]), array([ 0.0001])),
 (array([ 0.1421]), array([ 0.119])),
 (array([-0.6485]), array([  2.2280e-10])),
 (array([ 6.3462]), array([  1.9395e-138])),
 (array([-33.9161]), array([ 0.])),
 (array([ 9.1021]), array([ 0.])),
 (array([-0.1232]), array([ 0.3087])),
 (array([ 1.0916]), array([  6.8450e-14])),
 (array([-0.4031]), array([ 0.0027])),
 (array([-0.0256]), array([ 0.3905])),
 (array([-2.1572]), array([  6.0506e-08])),
 (array([ 0.0336]), array([ 0.2765])),
 (array([-0.95]), array([  2.1984e-63]))]

In [91]:
[coef_p[i][1] < 0.01 for i in range(0,len(coef_p))]

[array([ True], dtype=bool),
 array([False], dtype=bool),
 array([ True], dtype=bool),
 array([ True], dtype=bool),
 array([ True], dtype=bool),
 array([ True], dtype=bool),
 array([False], dtype=bool),
 array([ True], dtype=bool),
 array([ True], dtype=bool),
 array([False], dtype=bool),
 array([ True], dtype=bool),
 array([False], dtype=bool),
 array([ True], dtype=bool)]

multiple linear regression

In [94]:
d.shape
Y = d[:,d.shape[1]-1:]
X = d[:,0:d.shape[1]-1]
print(X.shape)

X = np.pad(X,1,'constant',constant_values=(1))[1:X.shape[0]+1,0:X.shape[1]+1]
print(X.shape)
X

(506, 13)
(506, 14)


array([[  1.0000e+00,   6.3200e-03,   1.8000e+01, ...,   1.5300e+01,
          3.9690e+02,   4.9800e+00],
       [  1.0000e+00,   2.7310e-02,   0.0000e+00, ...,   1.7800e+01,
          3.9690e+02,   9.1400e+00],
       [  1.0000e+00,   2.7290e-02,   0.0000e+00, ...,   1.7800e+01,
          3.9283e+02,   4.0300e+00],
       ..., 
       [  1.0000e+00,   6.0760e-02,   0.0000e+00, ...,   2.1000e+01,
          3.9690e+02,   5.6400e+00],
       [  1.0000e+00,   1.0959e-01,   0.0000e+00, ...,   2.1000e+01,
          3.9345e+02,   6.4800e+00],
       [  1.0000e+00,   4.7410e-02,   0.0000e+00, ...,   2.1000e+01,
          3.9690e+02,   7.8800e+00]])

In [95]:
beta = np.linalg.inv(np.transpose(X).dot(X)).dot(np.transpose(X).dot(Y))
beta

array([[  3.6459e+01],
       [ -1.0801e-01],
       [  4.6420e-02],
       [  2.0559e-02],
       [  2.6867e+00],
       [ -1.7767e+01],
       [  3.8099e+00],
       [  6.9222e-04],
       [ -1.4756e+00],
       [  3.0605e-01],
       [ -1.2335e-02],
       [ -9.5275e-01],
       [  9.3117e-03],
       [ -5.2476e-01]])

In [99]:
Y_hat = X.dot(beta)
Y_hat, Y

(array([[ 30.0038],
        [ 25.0256],
        [ 30.5676],
        [ 28.607 ],
        [ 27.9435],
        [ 25.2563],
        [ 23.0018],
        [ 19.536 ],
        [ 11.5236],
        [ 18.9203],
        [ 18.9995],
        [ 21.5868],
        [ 20.9065],
        [ 19.5529],
        [ 19.2835],
        [ 19.2975],
        [ 20.5275],
        [ 16.9114],
        [ 16.178 ],
        [ 18.4061],
        [ 12.5239],
        [ 17.671 ],
        [ 15.8329],
        [ 13.8063],
        [ 15.6783],
        [ 13.3867],
        [ 15.464 ],
        [ 14.7085],
        [ 19.5474],
        [ 20.8764],
        [ 11.4551],
        [ 18.0592],
        [  8.8111],
        [ 14.2828],
        [ 13.7068],
        [ 23.8146],
        [ 22.3419],
        [ 23.1089],
        [ 22.915 ],
        [ 31.3576],
        [ 34.2151],
        [ 28.0206],
        [ 25.2039],
        [ 24.6098],
        [ 22.9415],
        [ 22.0967],
        [ 20.4232],
        [ 18.0366],
        [  9.1066],
        [ 17.2061],


In [101]:
def lm_multi(X, Y):
    beta = np.linalg.inv(np.transpose(X).dot(X)).dot(np.transpose(X).dot(Y))
    Y_hat = X.dot(beta)
    return(beta, Y_hat)
        